### PR TITLE
Update for changes to DeviantART since...Wix acquisition, I think

### PR DESCRIPTION
**Pull request by SecantSystems**
DA has changed how they store their files.  The most obvious change is that the URLs are no longer ```username.deviantart.com``` but now ```deviantart.com/username```.  Secondly, the link in the download button has no file extension in it, so we have to get that information from the download button's text field (otherwise it grabs a bunch of alphanumeric garbage from the URL to be the file extension).

### CODE REVIEW

**Comment by xofred** [comment]
Cool, have u check the situation need login or adult content, too? Cuz DA might have different CSS selector for them. If all check fine, should be good to go

**Comment by SecantSystems** [comment]
Yeah, it logs in and grabs mature content just fine.  It looks like DA's only made backend changes (so far).

**Comment by xofred** [comment]
Hmm...I tried `http://azoexevan.deviantart.com/gallery/` but seems file names are still with numbers attached. How about your side?
image

**Comment by SecantSystems** [comment]
That was like that before -- that's the 'file ID' (see lines 256 and 271) from the end of the page URL.  It's useful because it's a globally unique ID that prevents filename collisions if the account has multiple artworks with identical titles.  When I said 'alphanumeric garbage', I meant something like "d6zdthx-aeac138e-ec7f-4c12-9be2-fa755a4545b1" (from the "experimento tableta" deviation).

**Comment by xofred** [comment]
Oh，switching back to `dev`, now I see the difference😂

**Pull request merged**
